<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ApiClient } from '../api'
import { useSessionStore } from '../stores/session'
import type { ReviewDecision, Urgency, Visit } from '../types'
import StatusPill from '../components/StatusPill.vue'

const session=useSessionStore(),api=new ApiClient(()=>session.token),queue=ref<Visit[]>([]),selected=ref<Visit|null>(null)
const reason=ref('已核对结构化信息、规则命中与公开教学引用'),finalUrgency=ref<Urgency>('ROUTINE'),decision=ref<ReviewDecision>('ACCEPT'),busy=ref(false),reviewed=ref<Visit|null>(null),planId=ref<string|null>(null)
const run=computed(()=>selected.value?.runs[0])
async function load(){queue.value=await api.queue();if(queue.value.length&&!selected.value)select(queue.value[0])}
function select(v:Visit){selected.value=v;reviewed.value=null;planId.value=null;decision.value='ACCEPT';finalUrgency.value=v.triage?.aiUrgency||v.triage?.ruleUrgency||'ROUTINE'}
async function review(){if(!selected.value?.triage)return;busy.value=true;try{const result=await api.review(selected.value.triage.id,decision.value,reason.value,finalUrgency.value);reviewed.value=result;queue.value=queue.value.filter(v=>v.id!==result.id);if(decision.value==='REJECT'){ElMessage.success('病例已拒绝，不会生成随访计划');selected.value=null;reviewed.value=null;await load()}else ElMessage.success('人工终审已保存，请单独确认是否创建计划')}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
async function createPlan(){if(!reviewed.value)return;busy.value=true;try{const plan=await api.createPlan(reviewed.value.id);planId.value=plan.id;ElMessage.success('随访计划草稿已创建，尚未激活')}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
async function activate(){if(!planId.value)return;try{await ElMessageBox.confirm('激活后会生成并分配 4 个教学随访任务。','确认激活',{type:'warning'});busy.value=true;await api.activatePlan(planId.value);ElMessage.success('教学随访计划已激活');selected.value=null;reviewed.value=null;planId.value=null;await load()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}finally{busy.value=false}}
onMounted(()=>load().catch((e:any)=>ElMessage.error(e.message)))
</script>

<template><section class="workspace"><div class="page-heading"><div><span class="eyebrow">CLINICAL REVIEW</span><h1>医务人员安全审核台</h1><p>审核决定与随访计划分步确认；拒绝病例不会进入后续任务。</p></div><div class="stat-card urgent"><strong>{{queue.length}}</strong><span>待人工审核</span></div></div>
  <div class="review-layout"><aside class="queue panel"><div class="panel-title"><h2>待处理队列</h2><span class="safe-chip">按提交时间</span></div><div v-if="!queue.length" class="empty">当前队列已清空。</div><button v-for="v in queue" :key="v.id" class="queue-item" :class="{active:selected?.id===v.id}" @click="select(v)"><div><strong>{{v.chiefComplaint}}</strong><small>{{new Date(v.submittedAt||v.createdAt).toLocaleString()}}</small></div><StatusPill :value="v.triage?.ruleUrgency" /></button></aside>
  <article v-if="selected" class="panel detail"><div class="detail-header"><div><span class="eyebrow">CASE {{selected.id.slice(0,8)}}</span><h2>{{selected.chiefComplaint}}</h2></div><StatusPill :value="reviewed?.status||'PENDING_REVIEW'" /></div><div class="evidence-grid"><div class="evidence-block"><h3>结构化症状</h3><div v-for="s in selected.symptoms" :key="s.code" class="fact"><span>{{s.name}} · {{s.code}}</span><strong>{{s.severity}} / 10</strong></div></div><div class="evidence-block risk"><h3>确定性规则</h3><StatusPill :value="selected.triage?.ruleUrgency" /><ul><li v-for="r in selected.triage?.ruleReasons" :key="r">{{r}}</li></ul></div></div>
    <div class="ai-block"><div class="ai-title"><h3>AI 辅助草案</h3><div><span class="provider">{{run?.provider||'fake'}} / {{run?.model}}</span><StatusPill :value="run?.status" /></div></div><p>{{selected.triage?.aiSummary||'AI 不可用或被阻断；请依据规则结果人工处理。'}}</p><div v-for="c in run?.citations" :key="c.chunkId" class="citation"><strong>{{c.title}} · {{c.section}}</strong><blockquote>{{c.quote}}</blockquote><small>Chunk: {{c.chunkId}} · <a :href="c.sourceUrl" target="_blank" rel="noreferrer">核对来源</a></small><p class="license">{{c.licenseNote}}</p></div><div v-if="run?.safetyReasons.length" class="warning">安全原因：{{run.safetyReasons.join('、')}}</div></div>
    <div class="review-form"><h3>人工终审</h3><div class="inline-fields three"><el-select v-model="decision" :disabled="!!reviewed"><el-option label="接受 ACCEPT" value="ACCEPT"/><el-option label="修改 MODIFY" value="MODIFY"/><el-option label="拒绝 REJECT" value="REJECT"/></el-select><el-select v-model="finalUrgency" :disabled="decision==='REJECT'||!!reviewed"><el-option label="常规 ROUTINE" value="ROUTINE"/><el-option label="紧急 URGENT" value="URGENT"/><el-option label="急症 EMERGENCY" value="EMERGENCY"/></el-select><el-input v-model="reason" :disabled="!!reviewed" placeholder="审核理由（必填）" /></div><el-button v-if="!reviewed" type="primary" size="large" :loading="busy" @click="review">保存审核决定</el-button><template v-else><div class="decision-banner">审核已保存：{{reviewed.triage?.reviewDecision}}。随访计划不会自动创建。</div><div class="button-row"><el-button v-if="!planId" type="primary" :loading="busy" @click="createPlan">创建随访计划草稿</el-button><el-button v-else type="success" :loading="busy" @click="activate">确认激活计划</el-button></div></template><small v-if="decision!=='REJECT'">系统会拒绝任何低于规则等级的最终结果。</small></div></article><article v-else class="panel empty large">选择一个病例开始审核。</article></div></section></template>
