<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { ElMessage } from 'element-plus'
import { ApiClient } from '../api'; import { useSessionStore } from '../stores/session'; import type { Urgency, Visit } from '../types'; import StatusPill from '../components/StatusPill.vue'
const session=useSessionStore(),api=new ApiClient(()=>session.token),queue=ref<Visit[]>([]),selected=ref<Visit|null>(null),reason=ref('已核对结构化信息、规则命中与公开教学引用'),finalUrgency=ref<Urgency>('ROUTINE'),busy=ref(false)
const run=computed(()=>selected.value?.runs[0]); async function load(){queue.value=await api.queue();if(queue.value.length&&!selected.value)select(queue.value[0])} function select(v:Visit){selected.value=v;finalUrgency.value=v.triage?.aiUrgency||v.triage?.ruleUrgency||'ROUTINE'}
async function review(){if(!selected.value?.triage)return;busy.value=true;try{const reviewed=await api.review(selected.value.triage.id,'ACCEPT',reason.value,finalUrgency.value);const plan=await api.createPlan(reviewed.id);await api.activatePlan(plan.id);ElMessage.success('审核完成，已激活教学随访计划');selected.value=null;await load()}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
onMounted(()=>load().catch((e:any)=>ElMessage.error(e.message)))
</script>
<template><section class="workspace"><div class="page-heading"><div><span class="eyebrow">CLINICAL REVIEW</span><h1>医务人员安全审核台</h1><p>规则是不可降低的安全底线；AI 草案与引用必须逐项核对后才能生成最终结果。</p></div><div class="stat-card urgent"><strong>{{queue.length}}</strong><span>待人工审核</span></div></div>
  <div class="review-layout"><aside class="queue panel"><div class="panel-title"><h2>待处理队列</h2><span class="safe-chip">按提交时间</span></div><div v-if="!queue.length" class="empty">当前队列已清空。</div><button v-for="v in queue" :key="v.id" class="queue-item" :class="{active:selected?.id===v.id}" @click="select(v)"><div><strong>{{v.chiefComplaint}}</strong><small>{{new Date(v.submittedAt||v.createdAt).toLocaleString()}}</small></div><StatusPill :value="v.triage?.ruleUrgency" /></button></aside>
  <article v-if="selected" class="panel detail"><div class="detail-header"><div><span class="eyebrow">CASE {{selected.id.slice(0,8)}}</span><h2>{{selected.chiefComplaint}}</h2></div><StatusPill value="PENDING_REVIEW" /></div><div class="evidence-grid"><div class="evidence-block"><h3>结构化症状</h3><div v-for="s in selected.symptoms" :key="s.code" class="fact"><span>{{s.name}} · {{s.code}}</span><strong>{{s.severity}} / 10</strong></div></div><div class="evidence-block risk"><h3>确定性规则</h3><StatusPill :value="selected.triage?.ruleUrgency" /><ul><li v-for="r in selected.triage?.ruleReasons" :key="r">{{r}}</li></ul></div></div>
    <div class="ai-block"><div class="ai-title"><h3>AI 辅助草案</h3><div><span class="provider">{{run?.provider||'fake'}} / {{run?.model}}</span><StatusPill :value="run?.status" /></div></div><p>{{selected.triage?.aiSummary||'AI 不可用或被阻断；请依据规则结果人工处理。'}}</p><div v-for="c in run?.citations" :key="c.chunkId" class="citation"><strong>{{c.title}} · {{c.section}}</strong><blockquote>{{c.quote}}</blockquote><small>Chunk: {{c.chunkId}}</small></div><div v-if="run?.safetyReasons.length" class="warning">安全原因：{{run.safetyReasons.join('、')}}</div></div>
    <div class="review-form"><h3>人工终审</h3><div class="inline-fields"><el-select v-model="finalUrgency"><el-option label="常规 ROUTINE" value="ROUTINE"/><el-option label="紧急 URGENT" value="URGENT"/><el-option label="急症 EMERGENCY" value="EMERGENCY"/></el-select><el-input v-model="reason" placeholder="审核理由（必填）" /></div><el-button type="primary" size="large" :loading="busy" @click="review">接受并激活随访计划</el-button><small>系统会拒绝任何低于规则等级的最终结果。</small></div></article><article v-else class="panel empty large">选择一个病例开始审核。</article></div></section></template>

