<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { CircleCheck, DocumentChecked, Files, WarningFilled } from '@element-plus/icons-vue'
import { ApiClient } from '../api'
import { formatDateTime, physiologicalInfoLabel, reasonLabel } from '../domain/presentation'
import { useSessionStore } from '../stores/session'
import type { ReviewDecision, SymptomReport, Urgency, Visit } from '../types'
import StatusPill from '../components/StatusPill.vue'

type PlanChoice='NONE'|'GENERAL_FOLLOWUP_V1'
const session=useSessionStore(),api=new ApiClient(()=>session.token)
const queue=ref<Visit[]>([]),selected=ref<Visit|null>(null),reviewed=ref<Visit|null>(null),busy=ref(false),planId=ref<string|null>(null)
const decision=ref<ReviewDecision>('ACCEPT'),finalUrgency=ref<Urgency>('ROUTINE'),reason=ref('已核对患者原话、事实答案、规则结果、覆盖状态与引用证据'),planChoice=ref<PlanChoice>('NONE')
const run=computed(()=>selected.value?.runs[0])
const aiSupport=computed(()=>selected.value?.triage?.aiSupport)
const coverageLabel:Record<string,string>={FULL:'已覆盖所选规则症状',PARTIAL:'部分症状仅作记录',NONE:'无对应确定性规则'}
const assessmentLabel:Record<string,string>={RULE_EVALUATED:'已执行确定性规则',REQUIRES_MANUAL_REVIEW:'必须人工评估'}
const factLabel:Record<string,string>={JUST_NOW:'刚刚',TODAY:'今天',ONE_TO_THREE_DAYS:'1–3 天',MORE_THAN_THREE_DAYS:'3 天以上',CONTINUOUS:'持续',INTERMITTENT:'间歇',RELIEVED:'已经缓解',PRESENT:'仍存在',NOT_PRESENT:'目前没有',NO_IMPACT:'不影响',NEEDS_REST:'需要停下休息',UNABLE_NORMAL_ACTIVITY:'无法正常活动',UNKNOWN:'不知道/说不清'}

async function load(){queue.value=await api.queue();if(queue.value.length&&!selected.value)select(queue.value[0])}
function select(visit:Visit){selected.value=visit;reviewed.value=null;planId.value=null;planChoice.value='NONE';decision.value='ACCEPT';finalUrgency.value=visit.triage?.aiUrgency||visit.triage?.ruleUrgency||'ROUTINE'}
function reportName(report:SymptomReport){return report.name||'未命名不适'}
function facts(report:SymptomReport){return [`开始：${factLabel[report.onsetRange||'UNKNOWN']||'未知'}`,`过程：${factLabel[report.course||'UNKNOWN']||'未知'}`,`现在：${factLabel[report.currentStatus||'UNKNOWN']||'未知'}`,`活动影响：${factLabel[report.activityImpact||'UNKNOWN']||'未知'}`]}
async function review(){if(!selected.value?.triage||!reason.value.trim())return ElMessage.warning('请填写人工审核理由');busy.value=true;try{const result=await api.review(selected.value.triage.id,decision.value,reason.value.trim(),finalUrgency.value);reviewed.value=result;queue.value=queue.value.filter(value=>value.id!==result.id);if(decision.value==='REJECT'){ElMessage.success('记录已退回人工处理，不会创建随访计划');selected.value=null;reviewed.value=null;await load()}else ElMessage.success('人工终审已保存，请继续明确随访决策')}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
async function confirmFollowup(){if(!reviewed.value)return;if(planChoice.value==='NONE'){ElMessage.success('已确认不创建随访计划');selected.value=null;reviewed.value=null;await load();return}busy.value=true;try{const plan=await api.createPlan(reviewed.value.id,planChoice.value);planId.value=plan.id;ElMessage.success('随访计划草稿已创建，激活后生成任务')}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
async function activate(){if(!planId.value)return;try{await ElMessageBox.confirm('激活后将生成并分配随访任务。','确认激活计划',{type:'warning',confirmButtonText:'确认激活',cancelButtonText:'暂不激活'});busy.value=true;await api.activatePlan(planId.value);ElMessage.success('随访计划已激活');selected.value=null;reviewed.value=null;planId.value=null;await load()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}finally{busy.value=false}}
onMounted(()=>load().catch((e:any)=>ElMessage.error(e.message)))
</script>

<template>
  <section class="workspace clinician-workspace">
    <div class="page-heading"><div><span class="eyebrow">人工审核工作区</span><h1>预问诊安全终审</h1><p>按患者原话、事实答案、规则与覆盖、AI 摘要和引用分层核对。</p></div><div class="stat-card urgent"><strong>{{queue.length}}</strong><span>待人工审核</span></div></div>
    <div class="workflow-strip" aria-label="审核工作流"><span class="active">1 患者信息</span><span>2 规则与证据</span><span>3 人工终审</span><span>4 随访决策</span></div>
    <div class="review-layout">
      <aside class="queue panel"><div class="panel-title"><div><Files/><h2>待处理队列</h2></div><span class="safe-chip">按提交时间</span></div><div v-if="!queue.length" class="empty-state"><CircleCheck/><strong>当前队列已清空</strong><p>新的预问诊记录会显示在这里。</p></div><button v-for="visit in queue" :key="visit.id" class="queue-item" :class="{active:selected?.id===visit.id}" type="button" @click="select(visit)"><div><strong>{{visit.chiefComplaint}}</strong><small>{{formatDateTime(visit.submittedAt||visit.createdAt)}}</small></div><StatusPill :value="visit.triage?.ruleUrgency||visit.triage?.assessmentStatus"/></button></aside>
      <article v-if="selected" class="panel detail">
        <div class="detail-header"><div><span class="eyebrow">记录 {{selected.id.slice(0,8)}}</span><h2>{{selected.chiefComplaint}}</h2><p>{{selected.freeText||'患者未补充自由描述'}}</p></div><StatusPill :value="reviewed?.status||'PENDING_REVIEW'"/></div>
        <section class="review-section"><div class="review-section-title"><span>01</span><div><h3>患者原话与事实答案</h3><p>原始主诉、手选症状和 AI 提取结果分开保存与展示。</p></div></div><blockquote class="patient-quote">“{{selected.chiefComplaint}}{{selected.freeText?'；'+selected.freeText:''}}”</blockquote><div class="fact-grid"><div v-for="report in selected.symptomReports" :key="report.id||report.symptomCode" class="fact-card"><span>{{reportName(report)}}</span><strong>{{report.source==='LEGACY'?'历史记录':'患者手动/问答记录'}}</strong><small v-for="item in facts(report)" :key="item">{{item}}</small><small v-if="report.answers.length">特异问题：{{report.answers.length}} 项已回答</small></div></div><div v-if="selected.complaintAnalysis?.status==='SUCCEEDED'" class="clinician-complaint-ai"><div><span class="step-kicker">患者确认的 AI 主诉整理</span><h4>{{selected.complaintAnalysis.normalizedSummary}}</h4></div><div class="clinician-tags"><span v-for="tag in selected.complaintAnalysis.tags.filter(tag=>tag.confirmationStatus!=='removed')" :key="tag.code" :class="tag.source==='ai_extracted'?'ai':'user'">{{tag.displayName}}<small>{{tag.source==='ai_extracted'?'AI 提取':'患者选择'}}</small></span></div><p v-if="selected.complaintAnalysis.uncertainties.length"><strong>不确定性：</strong>{{selected.complaintAnalysis.uncertainties.join('；')}}</p></div><div v-if="selected.profileSnapshot" class="profile-snapshot"><strong>提交时健康资料快照</strong><span>年龄段：{{selected.profileSnapshot.ageBand}}</span><span>生理情况：{{physiologicalInfoLabel(selected.profileSnapshot.physiologicalInfo)}}</span><span>慢病：{{selected.profileSnapshot.chronicConditions.join('、')||selected.profileSnapshot.chronicConditionsStatus}}</span><span>过敏：{{selected.profileSnapshot.allergies.join('、')||selected.profileSnapshot.allergiesStatus}}</span><span>长期用药：{{selected.profileSnapshot.longTermMedications.join('、')||selected.profileSnapshot.longTermMedicationsStatus}}</span></div></section>
        <section class="review-section"><div class="review-section-title"><span>02</span><div><h3>规则、AI 辅助与引用证据</h3><p>客观信息、知识库参考、AI 建议和不确定性严格分层；AI 不改变确定性规则。</p></div></div><div class="evidence-grid"><div class="evidence-block risk"><div class="evidence-heading"><h4>确定性规则</h4><StatusPill :value="selected.triage?.ruleUrgency||selected.triage?.assessmentStatus"/></div><p><strong>覆盖：</strong>{{coverageLabel[selected.triage?.coverageStatus||'NONE']}}</p><p><strong>评估：</strong>{{assessmentLabel[selected.triage?.assessmentStatus||'REQUIRES_MANUAL_REVIEW']}}</p><ul><li v-for="code in selected.triage?.ruleReasons" :key="code">{{reasonLabel(code)}} <small>({{code}})</small></li></ul></div><div class="evidence-block"><div class="evidence-heading"><h4>AI 结构化摘要</h4><StatusPill :value="run?.status"/></div><p>{{aiSupport?.structuredSummary||selected.triage?.aiSummary||'自动整理不可用，请依据患者事实和规则结果人工处理。'}}</p><small>{{run?.provider||'未运行'}} / {{run?.model||'—'}}</small></div></div><div v-if="aiSupport" class="ai-support-grid"><article><h4>关键症状与异常信息</h4><ul><li v-for="item in [...aiSupport.keyFindings,...aiSupport.abnormalSignals]" :key="item">{{item}}</li><li v-if="!aiSupport.keyFindings.length&&!aiSupport.abnormalSignals.length">未提取到额外异常信息</li></ul></article><article><h4>建议进一步追问</h4><ul><li v-for="item in aiSupport.missingQuestions" :key="item">{{item}}</li></ul></article><article><h4>重点排查与补充信息</h4><ul><li v-for="item in [...aiSupport.areasToRuleOut,...aiSupport.recommendedAdditionalInformation]" :key="item">{{item}}</li></ul></article><article class="risk"><h4>危险信号与不确定性</h4><ul><li v-for="item in [...aiSupport.riskSignals,...aiSupport.uncertainties]" :key="item">{{item}}</li></ul></article><article class="wide"><h4>证据综合</h4><p>{{aiSupport.evidenceSynthesis}}</p><small>{{aiSupport.disclaimer}}</small></article></div><details v-if="run?.citations.length" class="citation-drawer"><summary>查看 {{run.citations.length}} 条引用证据</summary><article v-for="citation in run.citations" :key="citation.chunkId" class="citation"><strong>{{citation.title}} · {{citation.section}}</strong><blockquote>{{citation.quote}}</blockquote><a :href="citation.sourceUrl" target="_blank" rel="noreferrer">核对公开来源</a><small>{{citation.licenseNote}}</small></article></details><div v-if="run?.safetyReasons.length" class="warning"><WarningFilled/>安全原因：{{run.safetyReasons.join('、')}}</div></section>
        <section class="review-section"><div class="review-section-title"><span>03</span><div><h3>人工终审</h3><p>存在规则紧急度时，系统会阻止降低；无自动等级时由医务人员判断。</p></div></div><div class="inline-fields three"><el-select v-model="decision" :disabled="!!reviewed"><el-option label="接受整理结果" value="ACCEPT"/><el-option label="人工修改" value="MODIFY"/><el-option label="退回处理" value="REJECT"/></el-select><el-select v-model="finalUrgency" :disabled="decision==='REJECT'||!!reviewed"><el-option label="常规" value="ROUTINE"/><el-option label="紧急" value="URGENT"/><el-option label="急症" value="EMERGENCY"/></el-select><el-input v-model="reason" :disabled="!!reviewed" maxlength="500" placeholder="人工审核理由（必填）"/></div><el-button v-if="!reviewed" type="primary" size="large" :loading="busy" :disabled="!reason.trim()" @click="review"><DocumentChecked/>保存人工终审</el-button><div v-else class="decision-banner"><CircleCheck/>审核已保存，系统没有自动创建随访。</div></section>
        <section v-if="reviewed" class="review-section followup-decision"><div class="review-section-title"><span>04</span><div><h3>明确随访决策</h3><p>默认不创建，需由医务人员明确选择并激活。</p></div></div><el-radio-group v-model="planChoice" class="plan-options" :disabled="!!planId"><el-radio value="NONE" border><strong>不创建随访</strong><small>本次记录在人工终审后结束</small></el-radio><el-radio value="GENERAL_FOLLOWUP_V1" border><strong>通用随访计划 v1</strong><small>激活后由随访人员执行任务</small></el-radio></el-radio-group><div class="button-row"><el-button v-if="!planId" type="primary" :loading="busy" @click="confirmFollowup">确认随访决策</el-button><el-button v-else type="success" :loading="busy" @click="activate">激活计划并生成任务</el-button></div></section>
      </article>
      <article v-else class="panel empty-state large"><DocumentChecked/><strong>选择一条记录开始审核</strong><p>每条记录都必须经过人工终审；随访计划不会自动创建。</p></article>
    </div>
  </section>
</template>
