<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { ElMessage } from 'element-plus'
import { ApiClient } from '../api'; import { useSessionStore } from '../stores/session'; import type { Task, Visit } from '../types'; import StatusPill from '../components/StatusPill.vue'
const session=useSessionStore(); const api=new ApiClient(()=>session.token); const visits=ref<Visit[]>([]),tasks=ref<Task[]>([]),submitting=ref(false)
const form=reactive({chiefComplaint:'合成胸痛伴呼吸困难',freeText:'仅为工程教学模拟，无真实个人信息。',symptoms:[{code:'CHEST_PAIN',name:'胸痛',severity:8,onset:'1 小时前'},{code:'DYSPNEA',name:'呼吸困难',severity:6,onset:'30 分钟前'}]})
async function load(){[visits.value,tasks.value]=await Promise.all([api.myVisits(),api.myTasks()])}
async function submit(){submitting.value=true;try{const draft=await api.createVisit(form);await api.submitVisit(draft.id);ElMessage.success('已完成规则筛查并进入人工审核队列');await load()}catch(e:any){ElMessage.error(e.message)}finally{submitting.value=false}}
onMounted(()=>load().catch((e:any)=>ElMessage.error(e.message)))
</script>
<template><section class="workspace"><div class="page-heading"><div><span class="eyebrow">PATIENT SIMULATION</span><h1>预问诊与我的随访</h1><p>只填写合成教学信息。提交后由规则先筛查，再由 AI 辅助整理并进入人工审核。</p></div><div class="stat-card"><strong>{{visits.length}}</strong><span>历史教学病例</span></div></div>
  <div class="two-column"><article class="panel"><div class="panel-title"><div><span class="step">01</span><h2>创建合成预问诊</h2></div><span class="safe-chip">合成数据</span></div>
    <el-form label-position="top"><el-form-item label="主要不适（合成描述）"><el-input v-model="form.chiefComplaint" /></el-form-item><div class="symptom-list"><div v-for="s in form.symptoms" :key="s.code" class="symptom-row"><div><strong>{{s.name}}</strong><small>{{s.code}}</small></div><el-slider v-model="s.severity" :min="0" :max="10" show-input /></div></div><el-form-item label="补充说明"><el-input v-model="form.freeText" type="textarea" :rows="3" maxlength="2000" show-word-limit /></el-form-item><div class="consent">✓ 我确认以上为虚构的成人教学病例，不包含真实个人或医疗数据。</div><el-button type="primary" size="large" :loading="submitting" @click="submit">提交并执行安全筛查</el-button></el-form>
  </article><aside class="panel"><div class="panel-title"><div><span class="step">02</span><h2>处理进度</h2></div></div><div v-if="!visits.length" class="empty">尚无病例，提交后可在此查看。</div><div v-for="v in visits" :key="v.id" class="case-card"><div class="case-head"><strong>{{v.chiefComplaint}}</strong><StatusPill :value="v.status" /></div><div class="risk-line" v-if="v.triage"><span>规则等级</span><StatusPill :value="v.triage.ruleUrgency" /></div><p v-if="v.triage">依据：{{v.triage.ruleReasons.join('、')}}</p><div v-if="v.runs[0]" class="run-line"><span>AI {{v.runs[0].provider}}</span><StatusPill :value="v.runs[0].status" /></div></div>
    <h3 class="section-label">我的随访任务</h3><div v-if="!tasks.length" class="empty compact">审核并激活计划后显示任务。</div><div v-for="task in tasks" :key="task.id" class="task-row"><div><strong>{{task.title}}</strong><small>{{new Date(task.dueAt).toLocaleDateString()}}</small></div><StatusPill :value="task.status" /></div></aside></div></section></template>

